### PR TITLE
Basic Auth support

### PR DESCRIPTION
**Pull request by kevinswiber**
This is a first pass at Basic Auth support.  We can continue a previous discussion from issue #78 related to pass-through.  At least there's something to point at now.

### CODE REVIEW

**Comment by loudej** [comment]
Wow - sorry for the delay - didn't see this out there. Will take a look.

**Comment by kevinswiber** [comment]
No problem.  This is a lightweight port from NRack (which was too eagerly OO for the functionality provided).  My thought is we can start picking this apart.

For passthrough, my only concern is setting the bounce-back point.  I almost think a "passthrough: true" parameter is needed for middleware.

**Comment by loudej** [comment]
I sent a horizontal pull request to you at https://github.com/kevinswiber/gate/pull/1 with some thoughts 

We should probably get some straw-man implementations of UseFormsAuth and UseOAuth2 to see how well those mix in

I tried using an IIdentity for the user variable, since it's baked in the CLR and has both a user name and an authentication type... Didn't go so far as to use an IPrincipal - bringing "roles" into the idea of authentication seems like something that is a different concern...

Forms will probably take cookies and session... Those concepts should be roughed in too - they're both in Rack - there's even a "rack.session" env key. (as I'm sure you're aware) :)

I don't like the long name based on the full namespace of IIdentity, really... Should we consider adding two more keys to the environment for Get<IIdentity>["owin.RemoteUser"]   Get<IDictionary<string,string>>["owin.Session"] ?

**Comment by ioleksiy** [comment]
On my opinion, Gate should support only basic functionality like it is now. Any Principals, and security things - are extensions, and they should go like extension. The only thing should be - pointer to session.

**Pull request closed without merging**
