### PR TITLE
Added Static middleware and supporting classes.

### PR DESCRIPTION
**Pull request by kevinswiber**
There are a lot of additions in here.  

Some points:
- One thing you'll want to look at is the BodyStream class.  It's used by the FileBody and TextBody classes.  BodyStream inherits StateMachine, which has some nice support for transition mapping and command eavesdropping.  This helped me figure out the differences between Kayak and ASP.NET host handlers recently.  It is, however, a re-implementation of some convenience methods on the Body class.  I'm not sure it's a complexity you want to take on, but I think it's worth it.
- Static uses FileServer to handle the bulk of the file handling.
- FileServer is written with future Sendfile middleware in mind, though this might take a different form when it finally materializes.
- File contents are currently streamed in 64KB buffers.  I looked at some prior art for this.  Rack sends 8KB chunks.  Connect (via Node.js) sends 64KB chunks.  I went high.
- Gate.Middleware took a dependency on Gate.Helpers.
- Static is built to take a directory as its root and a white-list of URL's.  In the absence of this configuration (Static.Create()), it defaults to the "public" directory and marks all directories and files underneath as white-listed.

Note: This is mostly a move over from NRack to Gate with the exception of the BodyStream, which was created to specifically to track state of the OWIN body delegate.

Curious to see some feedback.

### CODE REVIEW

**Comment by kevinswiber** [comment]
@bvanderveen said: "I kinda like that StateMachine class. Could you factor BodyStream so that it has-a StateMachine rather than is-a StateMachine?"

The BodyStream class kinda _is_ a StateMachine.  Can you elaborate on why?

@bvanderveen said: "Hm, I don't want Gate.Middleware to take that dependency. Could you move what's needed into Gate.Middleware?"

I hear what you're sayin'.  I don't like taking on package dependencies, either.  I put things like HttpFormatExtensions, RangeHeader, BodyStream, FileBody, and TextBody in Gate.Helpers, because they have uses scoped outside the purpose of Gate.Middleware.  You could potentially use them in an app without requiring the Middleware library.  The other option is to put them in Gate, but I don't think that's right, either.  Thoughts?

@bvanderveen: "Also, could you include tests for all this stuff?"

Yeah, for sure!  Honestly, this has been sitting on my box for a few days (under a Gate Sample App project).  With some controversial changes in here, I wanted to get it out sooner than later.  You can think of this more as a "request for comments" instead of a "ready for merge" PR.  I have to migrate some tests over from NRack and create some new ones.  Will do.

**Comment by kevinswiber** [comment]
Through some discussion and personal reflection, I conceded to all your requests.  :)

More tests should be added for some of the supporting files, but I've added a good start.  I'll add more when I get a little time.

**Comment by kevinswiber** [comment]
This is in pretty decent shape now if you guys (@bvanderveen, @loudej) are ready to evaluate for merging.

**Comment by bvanderveen** [comment]
Kevin, this code looks good, but could you make a new branch with a cleaned-up history and open a pull for that? This one seems to have some weird history—some commits repeated 3 times, and there are a few differences between them. Perhaps branch from the latest master and rebase/cherry-pick your changes back onto it?

**Comment by kevinswiber** [comment]
Sure.  Check out Pull Request [#48](https://github.com/owin/gate/pull/48).  It surprises me that Git would have a problem merging this.  I pulled in upstream changes for the last commit.  That's why you see some dupes.  It's showing a rebase with all the previous commits on the branch re-applied.

FYI:

I grabbed the list from 

```
git diff --name-only master static_middleware
```

Then, from master, I did:

```
git checkout -b static_middleware_clean
git checkout static_middleware -- <space-separated file list from above command>
```

That way, it just grabs the files from HEAD on static_middleware instead of bringing over any wacky commits.  Pull Request [#48](https://github.com/owin/gate/pull/48) should be pretty clean.

**Comment by loudej** [comment]
Sorry - I'm coming late into the conversation! I added comments in the new pull request. We should close this one probably.

**Pull request closed without merging**
