### PR TITLE
Added a few things to the Gate.AspNet, and removed the "Ext" builder

### PR DESCRIPTION
**Pull request by loudej**
Fixed a bug where app delegate was being built more than once

Also added an IHttpHandler, which people can use instead of the module if they want the rest of the pipeline to run.

Also removes the "Ext" AppBuilder and added IAppBuilder extension methods for AppAction because it appears that the AppDelegate delegate and AppAction Func are not mutually ambiguous after all.

Cheers!
Lou

### CODE REVIEW

**Comment by bvanderveen** [comment]
Merged. I sliced up these commits a bit differently, and removed the Workaround.cs added to Kayak (couldn't tell what it was for; the tests passed without it being there). Thank you!

**Comment by loudej** [comment]
Sounds great. The workaround was from a compiler error that seems to
show up every so often when delegates are used implicitly in a lib...
It's quirky, if you aren't seeing the problem that's fine.

## 

Louis - sent from mobile From: bvanderveen
Sent: Monday, September 05, 2011 4:43 PM
To: louis.dejardin@gmail.com
Subject: Re: [gate] Added a few things to the Gate.AspNet, and removed
the "Ext" builder (#42)
Merged. I sliced up these commits a bit differently, and removed the
Workaround.cs added to Kayak (couldn't tell what it was for; the tests
passed without it being there). Thank you!

##

**Comment by bvanderveen** [comment]
Oh crazy. You were seeing this when referencing Gate or Gate.Kayak from another project entirely?

**Comment by loudej** [comment]
Yeah, when referencing Gate from another library.

**Pull request closed without merging**
